<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.wildfly.a2a</groupId>
        <artifactId>a2a-jakarta-parent</artifactId>
        <version>1.0.1.Final-SNAPSHOT</version>
    </parent>

    <artifactId>a2a-jakarta-tests-parent</artifactId>

    <packaging>pom</packaging>

    <name>WildFly Extras - A2A Jakarta - Tests - Parent</name>
    <description>Java SDK for the Agent2Agent Protocol (A2A) - SDK - Jakarta - Tests - Parent</description>

    <properties>
        <central.skipPublishing>true</central.skipPublishing>
    </properties>
    <modules>
        <module>common</module>
        <module>jsonrpc</module>
        <module>grpc</module>
        <module>rest</module>
        <module>compat-0.3</module>
        <module>multiversion</module>
        <module>multitenancy</module>
    </modules>
</project>
