<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.wildfly.a2a</groupId>
        <artifactId>a2a-jakarta-tests-parent</artifactId>
        <version>1.0.0.Final</version>
    </parent>

    <artifactId>a2a-jakarta-tests-compat-0.3-parent</artifactId>

    <packaging>pom</packaging>

    <name>WildFly Extras - A2A Jakarta - v0.3 Compat Tests - Parent</name>
    <description>Jakarta SDK for the Agent2Agent Protocol (A2A) - v0.3 Compat Tests - Parent</description>

    <modules>
        <module>rest</module>
        <module>jsonrpc</module>
        <module>grpc</module>
    </modules>
</project>
